### ISSUE TITLE
Errors with ETS6 Projects !

### ISSUE THREAD

**Issue by vincegre** [laurent-martin/ets-to-homeassistant#13]
Hi

I tried to use your tool with a basic ETS6 project but it fails with some Ruby errors:

```
vincen@pingouin-portable:~/ets-to-homeassistant$ ./ets_to_hass.rb --format /home/vincen/Bureau/Formation\ tout\ en\ 3.knxproj --ha-knx > /home/vincen/Bureau/ha.yaml
./ets_to_hass.rb:159: syntax error, unexpected ','
        type:,
./ets_to_hass.rb:160: syntax error, unexpected ',', expecting `end'
....map { |g| g['RefId'].freeze },
./ets_to_hass.rb:162: syntax error, unexpected '}', expecting `end'
      }.merge(info)
./ets_to_hass.rb:264: syntax error, unexpected `end', expecting end-of-input

```

Any chance to get the problem fixed ?

Thanks

Vincèn

**Comment by laurent-martin** [comment]
In case you can share a small ETS6 project, I can have a look.

**Comment by zeev-mindali** [comment]
here is my test project that you can check:
[test.knxproj.zip](https://github.com/laurent-martin/ets-to-homeassistant/files/13683346/test.knxproj.zip)

**Comment by MelindaJaphines** [comment]
Hey

I was also wondering if there is a plan to support ETS6 projects in the future?

**Comment by laurent-martin** [comment]
I think that un-encrypted projects should work.
But currently password-protected projects are not supported yet.
Is your project password protected?

**Comment by fapo85** [comment]
I have also created a test project without password protection for testing purposes.
P-01C0.info also states that it is not protected.

It is a minimal project with a glass pushbutton and a universal actuator

Error:

```
C:/Users/fabia/SourceRepos/ets-to-homeassistant/lib/ets_to_hass/generator.rb:122:in 'EtsToHass::Generator#read_file': Did not find project information or data ([:data]) (RuntimeError)
        from C:/Users/fabia/SourceRepos/ets-to-homeassistant/lib/ets_to_hass/generator.rb:71:in 'EtsToHass::Generator#initialize'
        from ./ets_to_hass:109:in 'Class#new'
        from ./ets_to_hass:109:in '<main>'
PS C:\Users\fabia\SourceRepos\ets-to-homeassistant\bin>
```

I have renamed the file from test.knxproj to zip
[test.zip](https://github.com/user-attachments/files/18540201/test.zip)

**Comment by laurent-martin** [comment]
Mmm,

I rename the file to `test1.zip` and run:

```console
$ ./bin/ets_to_hass examples/test1.knxproj
I, [2025-01-26T12:05:04.106192 #42283]  INFO -- : Project: P-01C0 found
I, [2025-01-26T12:05:04.106224 #42283]  INFO -- : Using project test, address style: ThreeLevel
W, [2025-01-26T12:05:04.106261 #42283]  WARN -- : No building information found.
W, [2025-01-26T12:05:04.106276 #42283]  WARN -- : 0/0/1 Lich Schalten Group not in object: use ETS to create functions or use specific code
W, [2025-01-26T12:05:04.106282 #42283]  WARN -- : 0/0/2 Lich Status Group not in object: use ETS to create functions or use specific code
# Generated by ets_to_hass
# Date: 2025-01-26 12:05:04 +0100
--- {}
```

I run on macos, I have checked on Windows, it worked as well.

The error message `Did not find project information or data ([:data])` means that the script did not find the file `P-01C0/project.xml` , but I see it is in there.

The output is empty here, it is normal: the script cannot infer alone which group belong to which objects.
This can be done either by creating "functions" in ETS, or by creating a ruby script that can infer those objects from the group names.

For example, in test.zip:
two group addresses:
0/0/1 Lich Schalten
0/0/2 Lich Status

From the name, it seems that both are part of the same object "Lich", but how the program can detect that ?
What I have planned, is the possibility also to add meta data in the description of group addresses.
