### ISSUE TITLE
Did not find project information or data ([])

### ISSUE THREAD

**Issue by phcollignon** [laurent-martin/ets-to-homeassistant#20]
Hello,

Thanks for well documented project.  However I'm facing an error at runtime :  
```` 
C:/Users/phili/.local/share/gem/ruby/3.2.0/gems/ets-to-homeassistant-0.1/lib/ets_to_hass/generator.rb:122:in `read_file': Did not find project information or data ([]) (RuntimeError)
        from C:/Users/phili/.local/share/gem/ruby/3.2.0/gems/ets-to-homeassistant-0.1/lib/ets_to_hass/generator.rb:71:in `initialize'
        from C:/Users/phili/.local/share/gem/ruby/3.2.0/gems/ets-to-homeassistant-0.1/bin/ets_to_hass:109:in `new'
        from C:/Users/phili/.local/share/gem/ruby/3.2.0/gems/ets-to-homeassistant-0.1/bin/ets_to_hass:109:in `<top (required)>'
        from C:/Users/phili/AppData/Local/Microsoft/WindowsApps/ets_to_hass:32:in `load'
        from C:/Users/phili/AppData/Local/Microsoft/WindowsApps/ets_to_hass:32:in `<main>'
````
My project is password protected ... is it related to the issue ?

**Comment by phcollignon** [comment]
I can confirm the password was the issue ... 
The workaround is to make a copy of the project, remove secured devices, clear project password and run it on that unprotected project
