### ISSUE TITLE
ETS5 Project - YAML File contains only "--- {}"

### ISSUE THREAD

**Issue by marko3122** [laurent-martin/ets-to-homeassistant#27]
> Hello,
> 
> My project has all the neccessary building information , however I did notice that none of my group addresses have the Data point type set. I've set some manually for testing , in the terminal I can see that It didn't skip those adresses now but in the yaml file there is still nothing to see but the "--- {}" line.

Nevermind, I found the "WARN -- : xyz Group not in object: use ETS to create functions or use specific code" Error as well. With amounts of corrections I will have to do, it comes close to doing it manually anway :(

![WohnhausBUG](https://github.com/laurent-martin/ets-to-homeassistant/assets/95704888/2dc03151-71c6-4387-8fda-61d50558a4b9)
![testyaml](https://github.com/laurent-martin/ets-to-homeassistant/assets/95704888/68454eb2-7a9f-442a-b23c-0122dfa6a384)

**Comment by laurent-martin** [comment]
Right,

As described in the README, the tool cannot guess how KNX group addresses are associated with H.A. objects.

This information needs to come from somewhere.

There are 2 possibilities:

1. in ETS, in building, create "functions" : one per H.A. objects, and place group addresses in those functions, (for example a light).
2. or, if the naming is processable, write some small ruby code that parses the group name and deduce an object type and name...

Personally, initially, I used 2. , but then I added 1, as it is more integrated with ETS.

I see you have building information: did you create the functions ?

<img width="283" alt="image" src="https://github.com/laurent-martin/ets-to-homeassistant/assets/11157566/2518cdb2-1f48-428b-a079-615fc804e1f7">


There are still some pitfalls: ETS functions are limited to a few only, and do not provide complex ones.
In a future release of this tool, it will be possible to include metadata in the comment part.

**Comment by TheFelix93** [comment]
@marko3122  how does it come that the DPTs are not set by ETS? I think always when I associated a GA with a device, like an actor, that writes to the GA the DPT was mapped automatically.

**Comment by marko3122** [comment]
> @marko3122 how does it come that the DPTs are not set by ETS? I think always when I associated a GA with a device, like an actor, that writes to the GA the DPT was mapped automatically.

No idea honestly, the owner decided to go with the "Horizone" visualization route so I won't be banging my head too much about this one

**Comment by Weimissing** [comment]
I've switched from using plain KNX group addresses to using ETS Functions (ETS6). However, the YAML file still only contains "--- {}". 
According to the debug notes, the script should run correctly.
Even the example-files won't work....
Style1.knxproj:

> D, [2025-12-23T12:42:09.323688 #13964] DEBUG -- : function: {name: "Ceiling light", type: :dimmable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
D, [2025-12-23T12:42:09.323790 #13964] DEBUG -- : function: {name: "Mirror", type: :switchable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
D, [2025-12-23T12:42:09.323891 #13964] DEBUG -- : function: {name: "Light room switch", type: :switchable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
D, [2025-12-23T12:42:09.324020 #13964] DEBUG -- : function: {name: "Window", type: :sun_protection, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
D, [2025-12-23T12:42:09.324126 #13964] DEBUG -- : function: {name: "Radiator", type: :heating_radiator, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
D, [2025-12-23T12:42:09.324274 #13964] DEBUG -- : function: {name: "Floor", type: :heating_floor, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}



Perhaps it's due to the 'No Method' error?

> PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:123:in 'block (2 levels) in Object#fix_objects': NoMethodError
        from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:118:in 'Array#each'
        from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:118:in 'block in Object#fix_objects'
        from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:100:in 'Array#each'
        from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:100:in 'Object#fix_objects'
        from PATH/AppData/Local/Temp/ocran002E9CE7E5E3/src/lib/ets_to_hass/generator.rb:375:in 'EtsToHass::Generator#generate_homeass'
        from PATH/AppData/Local/Temp/ocran002E9CE7E5E3/src/bin/ets_to_hass:128:in '<main>'

**Comment by TheFelix93** [comment]
It's definitely because of the error. I see that you used the ui/exe version. I will the the sample.knxproj, on my side.

**Comment by TheFelix93** [comment]
> I've switched from using plain KNX group addresses to using ETS Functions (ETS6). However, the YAML file still only contains "--- {}". According to the debug notes, the script should run correctly. Even the example-files won't work.... Style1.knxproj:
> 
> > D, [2025-12-23T12:42:09.323688 #13964] DEBUG -- : function: {name: "Ceiling light", type: :dimmable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> > D, [2025-12-23T12:42:09.323790 #13964] DEBUG -- : function: {name: "Mirror", type: :switchable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> > D, [2025-12-23T12:42:09.323891 #13964] DEBUG -- : function: {name: "Light room switch", type: :switchable_light, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> > D, [2025-12-23T12:42:09.324020 #13964] DEBUG -- : function: {name: "Window", type: :sun_protection, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> > D, [2025-12-23T12:42:09.324126 #13964] DEBUG -- : function: {name: "Radiator", type: :heating_radiator, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> > D, [2025-12-23T12:42:09.324274 #13964] DEBUG -- : function: {name: "Floor", type: :heating_floor, ha: {domain: nil}, floor: "Upper floor", room: "Bath room"}
> 
> Perhaps it's due to the 'No Method' error?
> 
> > PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:123:in 'block (2 levels) in Object#fix_objects': NoMethodError
> > from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:118:in 'Array#each'
> > from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:118:in 'block in Object#fix_objects'
> > from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:100:in 'Array#each'
> > from PATH/ets-to-homeassistant-master/lib/ets_to_hass/specific/TheFelix93.rb:100:in 'Object#fix_objects'
> > from PATH/AppData/Local/Temp/ocran002E9CE7E5E3/src/lib/ets_to_hass/generator.rb:375:in 'EtsToHass::Generator#generate_homeass'
> > from PATH/AppData/Local/Temp/ocran002E9CE7E5E3/src/bin/ets_to_hass:128:in ''

It seems to be a problem with a fallback if no or invalid Attribute was found in a light function. When I test with the style1.knxproj I first get debug messages that indicate a light function with a GA with dpt 5.001 which is percentage. The script needs a correct attribute name pattern to recognize if it's the percentage set value or status. 
Nevertheless there should not be a 'no method error' at all because of this. There is a bug or something. I need to debug into this to see the cause. I am not sure when I have time, but I will reply again.
I can only suggest to study my documentation here.[https://github.com/TheFelix93/ets-to-homeassistant](url).

This issue entry is part of the initial project from martin, but the code causing the problem is likely to be in my fork.
