### ISSUE TITLE
which version of ruby are you running ?

### ISSUE THREAD

**Issue by schlaubi666** [laurent-martin/ets-to-homeassistant#3]
i use the latest dockerimage and installed zip xml-simle & yaml

i got the error:
no specific code, set env var SPECIAL to load specific code
ets_to_hass.rb:15:in `initialize': uninitialized constant Zip::File (NameError)
        from ets_to_hass.rb:152:in `new'
        from ets_to_hass.rb:152:in `<main>'

**Comment by schlaubi666** [comment]
gem install rubyzip was nessesary
